In [1]:
import pandas as pd

In [2]:
na_vals = ["NA","Missing"]
df=pd.read_csv('data/survey_results_public.csv',na_values=na_vals)

In [3]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Appropriate in length,Easy

In [4]:
df.shape

(88883, 80)

In [5]:
pd.set_option('display.max_columns',80)
pd.set_option('display.max_rows',80)
pd.set_option("display.min_rows",80)
pd.set_option('display.max_colwidth', None)   #cumlelerın hepsını gorebılmek için

In [27]:
schema_df=pd.read_csv('data/survey_results_schema.csv')

In [28]:
schema_df

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order of survey response time)
1,MainBranch,"Which of the following options best describes you today? Here, by ""developer"" we mean ""someone who writes code."""
2,Hobbyist,Do you code as a hobby?
3,OpenSourcer,How often do you contribute to open source?
4,OpenSource,How do you feel about the quality of open source software (OSS)?
5,Employment,Which of the following best describes your current employment status?
6,Country,In which country do you currently reside?
7,Student,"Are you currently enrolled in a formal, degree-granting college or university program?"
8,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed?
9,UndergradMajor,What was your main or most important field of study?
10,EduOther,Which of the following types of non-degree education have you used or participated in? Please select all that apply.
11,OrgSize,Approximately how many people are employed by the company or organization you work for?
12,DevType,Which of the following describe you? Please select all that apply.
13,YearsCode,"Including any education, how many years have you been coding?"
14,Age1stCode,"At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scratch project)"
15,YearsCodePro,How many years have you coded professionally (as a part of your work)?
16,CareerSat,"Overall, how satisfied are you with your career thus far?"
17,JobSat,"How satisfied are you with your current job? (If you work multiple jobs, answer for the one you spend the most hours on.)"
18,MgrIdiot,How confident are you that your manager knows what they’re doing?
19,MgrMoney,Do you believe that you need to be a manager to make more money?
20,MgrWant,Do you want to become a manager yourself in the future?
21,JobSeek,Which of the following best describes your current job-seeking status?
22,LastHireDate,When was the last time that you took a job with a new employer?
23,LastInt,"In your most recent successful job interview (resulting in a job offer), you were asked to... (check all that apply)"
24,FizzBuzz,Have you ever been asked to solve FizzBuzz in an interview?
25,JobFactors,"Imagine that you are deciding between two job offers with the same compensation, benefits, and location. Of the following factors, which 3 are MOST important to you?"
26,ResumeUpdate,"Think back to the last time you updated your resumé, CV, or an online profile on a job site. What is the PRIMARY reason that you did so?"
27,CurrencySymbol,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."
28,CurrencyDesc,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in."
29,CompTotal,"What is your current total compensation (salary, bonuses, and perks, before taxes and deductions), in `CurrencySymbol`? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent weekly, monthly, or yearly salary. If you prefer not to answer, please leave the box empty."
30,CompFreq,"Is that compensation weekly, monthly, or yearly?"
31,ConvertedComp,"Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 working months and 50 working weeks."
32,WorkWeekHrs,"On average, how many hours per week do you work?"
33,WorkPlan,How structured or planned is your work?
34,WorkChallenge,"Of these options, what are your greatest challenges to productivity as a developer? Select up to 3:"
35,WorkRemote,How often do you work remotely?
36,WorkLoc,Where would you prefer to work?
37,ImpSyn,"For the specific work you do, and the years of experience you have, how do you rate your own level of competence?"
38,CodeRev,Do you review code as part of your work?
39,CodeRevHrs,"On average, how many hours per week do you spend on code review?"
40,UnitTests,Does your company regularly employ unit tests in the development of their products?
41,PurchaseHow,"How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?"
42,PurchaseWhat,"What level of influence do you, personally, have over new technology purchases at your organization?"
43,LanguageWorkedWith,"Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"
44,LanguageDesireNextYear,"Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)"
45,DatabaseWorkedWith,"Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"
46,DatabaseDesireNextYear,"Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)"
47,PlatformWorkedWith,"Which of the following platforms have you done extensive development work for over the past year? (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)"
48,PlatformDesireNextYear,"Which of the following platforms have you done extensive development work for over the past year? (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)"
49,WebFrameWorkedWith,"Which of the following web frameworks have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)"
50,WebFrameDesireNextYear,"Which of the following web frameworks have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the framework and want to continue to do so, please check both boxes in that row.)"
51,MiscTechWorkedWith,"Which of the following other frameworks, libraries, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the technology and want to continue to do so, please check both boxes in that row.)"
52,MiscTechDesireNextYear,"Which of the following other frameworks, libraries, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the technology and want to continue to do so, please check both boxes in that row.)"
53,DevEnviron,Which development environment(s) do you use regularly? Please check all that apply.
54,OpSys,What is the primary operating system in which you work?
55,Containers,"How do you use containers (Docker, Open Container Initiative (OCI), etc.)?"
56,BlockchainOrg,How is your organization thinking about or implementing blockchain technology?
57,BlockchainIs,Blockchain / cryptocurrency technology is primarily:
58,BetterLife,Do you think people born today will have a better life than their parents?
59,ITperson,"Are you the ""IT support person"" for your family?"
60,OffOn,Have you tried turning it off and on again?
61,SocialMedia,What social media site do you use the most?
62,Extraversion,Do you prefer online chat or IRL conversations?
63,ScreenName,What do you call it?
64,SOVisit1st,"To the best of your memory, when did you first visit Stack Overflow?"
65,SOVisitFreq,How frequently would you say you visit Stack Overflow?
66,SOVisitTo,I visit Stack Overflow to... (check all that apply)
67,SOFindAnswer,"On average, how many times a week do you find (and use) an answer on Stack Overflow?"
68,SOTimeSaved,"Think back to the last time you solved a coding problem using Stack Overflow, as well as the last time you solved a problem using a different resource. Which was faster?"
69,SOHowMuchTime,"About how much time did you save? If you're not sure, please use your best estimate."
70,SOAccount,Do you have a Stack Overflow account?
71,SOPartFreq,"How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean ask, answer, vote for, or comment on questions."
72,SOJobs,Have you ever used or visited Stack Overflow Jobs?
73,EntTeams,Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
74,SOComm,Do you consider yourself a member of the Stack Overflow community?
75,WelcomeChange,"Compared to last year, how welcome do you feel on Stack Overflow?"
76,SONewContent,Would you like to see any of the following on Stack Overflow? Check all that apply.
77,Age,"What is your age (in years)? If you prefer not to answer, you may leave this question blank."
78,SurveyLength,How do you feel about the length of the survey this year?
79,SurveyEase,How easy or difficult was this survey to complete?

In [8]:
df.head(10)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Courses on technologies you're interested in,14.0,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,"Financial performance or funding status of the company or organization;Specific department or team I'd be working on;Languages, frameworks, and other technologies I'd be working with","Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,19.0,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time or a flexible schedule",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company culture;Opportunities for professional development",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,22.0,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software","10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Developer, mobile",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Interview with people in senior / management roles",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working with;Flex time or a flexible schedule",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments (parenting, school work, hobbies, etc.)",A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Appropriate in length,Easy
5,6,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,"Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course",NaN,"Data or business analyst;Data scientist or machine learning specialist;Database administrator;Engineer, data",13,15,3,Very satisfied,Slightly satisfied,Very confident,No,Yes,I am not interested in new job opportunities,1-2 years ago,Write any code;Complete a take-home project;Interview with people in senior / management roles,No,Financial performance or funding status of the company or organization;Opportunities for professional development;How widely used or impactful my work output would be,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",CAD,Canadian dollar,40000.0,Monthly,366420.0,15.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,A few days each month,Home,A little above average,No,NaN,"Yes, it's not part of our process but the developers do it on their own",Not sure,I have little or no influence,Java;R;SQL,Python;Scala;SQL,MongoDB;PostgreSQL,PostgreSQL,Android;Google Cloud Platform;Linux;Windows,Android;Google Cloud Platform;Linux;Windows,NaN,NaN,Hadoop,Hadoop;Pandas;TensorFlow;Unity 3D,Android Studio;Eclipse;PyCharm;RStudio;Visual Studio Code,Windows,I do not use containers,Not at all,NaN,No,Yes,No,YouTube,In real life (in person),Login,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Overflow,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Too long,Neither easy nor difficult
6,7,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,"Independent contractor, freelancer, or self-employed",Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, electrical, mechanical)","Taught yourself a new language, framework, or tool without taking a formal course","Just me - I am a freelancer, sole proprietor, etc.","Designer;Developer, front-end",6,17,4,Slightly satisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",NA - I am an independent contractor or self employed,Write any code,No,Remote work options;Opportunities for professional development;Flex time or a flexible schedule,NaN,USD,United States dollar,NaN,NaN,NaN,32.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Being tasked with non-development work;Distracting work environment;Non-work commitments (parenting, school work, hobbies, etc.)",All or almost all the time (I'm full-time remote),"Other place, such as a coworking space or cafe",Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,HTML/CSS;JavaScript,HTML/CSS;JavaScript,NaN,NaN,MacOS;Windows,MacOS;Windows,React.js,React.js,NaN,NaN,PHPStorm,Windows,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,No,YouTube,NaN,NaN,2014,Daily or almost daily,Find answers to specific questions,3-5 times per week,NaN,NaN,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Neutral,A lot more welcome now than last year,NaN,42.0,Appropriate in length,Neither easy nor difficult
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taught yourself a new language, framework, or tool without taking a formal course;Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder);Contributed to open source software",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;Python;SQL,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;Python;SQL;WebAssembly,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;Redis;SQLite,Cassandra;DynamoDB;Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQL;Redis,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platform;IBM Cloud or Watson;Kubernetes;Linux;MacOS;Raspberry Pi;Slack,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Pandas;Puppet;React Native;TensorFlow;Torch/PyTorch;Unreal Engine,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual Studio Code,Linux-based,"Development;Testing;Production;Outside of work, for personal projects",NaN,Useful across many domains and could change many aspects of our lives,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Contribute to a library of information,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,24.0,Appropriate in length,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software is about the same,Employed full-time,New Zealand,No,Some college/university study without earning a degree,"Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Participated in a full-time developer training program or bootcamp;Taken a part-time in-person course in programming or software development;Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course;Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder);Contributed to open source software",10 to 19 employees,"Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, QA or test;DevOps specialist",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,Write any code;Interview with people in peer roles;Interview with people in senior / management roles,Yes,Financial performance or funding status of the company or organization;Office environment or company culture;How widely used or impactful my work output would be,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Being tasked with non-development work;Inadequate access to necessary tools;Not enough people for the workload,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the developers do it on their own",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;Python;Ruby;Rust;SQL;TypeScript;WebAssembly;Other(s):,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ruby;Rust;SQL;TypeScript;WebAssembly;Other(s):,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute to a library of information,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Appropriate in length,Neither easy nor difficult

In [9]:
df.tail(10)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
88873,88062,NaN,No,Never,"OSS is, on average, of LOWER quality than proprietary / closed source software",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88874,88076,NaN,No,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88875,88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),10 to 19 employees,Academic researcher,1,Younger than 5 years,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,NaN,NaN,NaN,Google Cloud Platform,NaN,Other(s):,NaN,Other(s):,NaN,Android Studio,Windows,Development,NaN,Useful across many domains and could change many aspects of our lives,Yes,Also Yes,What?,Twitter,Neither,Username,NaN,I have never visited Stack Overflow (before today),Get a sense of belonging to the developer community,Less than once per week,The other resource was slightly faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Not applicable - I did not use Stack Overflow last year,Courses on technologies you're interested in,NaN,Too short,Neither easy nor difficult
88876,88212,NaN,No,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Spain,No,"Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,"Taught yourself a new language, framework, or tool without taking a formal course",10 to 19 employees,"Designer;Developer, front-end;Developer, full-stack",18,7,15,NaN,NaN,Somewhat confident,Yes,I am already a manager,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python,JavaScript,MySQL;PostgreSQL,PostgreSQL,NaN,Arduino,Django;React.js,Django;React.js,NaN,NaN,Atom;Visual Studio Code,MacOS,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of currency,No,SIGH,No,WhatsApp,In real life (in person),Username,2008,A few times per week,Find answers to specific questions,6-10 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Overflow,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are","No, not at all",NaN,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area,40.0,Appropriate in length,Easy
88877,88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",United States,No,Some college/university study without earning a degree,"Computer science, computer engineering, or software engineering","Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software",NaN,"Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, game or graphics;System administrator",38,10,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;WebAssembly,Bash/Shell/PowerShell;C;Go;HTML/CSS;JavaScript;WebAssembly,NaN,NaN,Linux,Linux;Raspberry Pi,React.js,Vue.js,Node.js,Ansible,Vim,Linux-based,I do not use containers,NaN,An irresponsible use of resources,No,NaN,Yes,I don't use social media,In real life (in person),Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Overflow,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Too short,Neither easy nor difficult
88878,88377,NaN,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Pass the time / relax,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Overflow,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","No, not at all",NaN,Tech articles written by other developers;Tech meetups or events in your area;Courses on technologies you're interested in,NaN,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software is about the same,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Taken a part-time in-person course in programming or software development;Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;PHP;SQL;Swift,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or Watson;iOS;Linux;MacOS;Slack;Windows,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++;Sublime Text,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Get a sense of belonging to the developer community,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,18.0,Appropriate in length,Easy

In [56]:
schema_df.head(10)

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order of survey response time)
1,MainBranch,"Which of the following options best describes you today? Here, by ""developer"" we mean ""someone who writes code."""
2,Hobbyist,Do you code as a hobby?
3,OpenSourcer,How often do you contribute to open source?
4,OpenSource,How do you feel about the quality of open source software (OSS)?
5,Employment,Which of the following best describes your current employment status?
6,Country,In which country do you currently reside?
7,Student,"Are you currently enrolled in a formal, degree-granting college or university program?"
8,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed?
9,UndergradMajor,What was your main or most important field of study?

In [10]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'SurveyLength',
       'SurveyEase'],
      dtype='str')

In [12]:
df["Hobbyist"].value_counts(dropna=False)   #none olanlarıda sayar

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [14]:
df.loc[1:10,"Hobbyist":"Employment"]

,Hobbyist,OpenSourcer,OpenSource,Employment
1,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time
3,No,Never,The quality of OSS and closed source software is about the same,Employed full-time
4,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time
5,Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time
6,No,Never,The quality of OSS and closed source software is about the same,"Independent contractor, freelancer, or self-employed"
7,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Not employed, but looking for work"
8,Yes,Once a month or more often,The quality of OSS and closed source software is about the same,Employed full-time
9,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time
10,Yes,Once a month or more often,The quality of OSS and closed source software is about the same,NaN

In [16]:
df["Hobbyist"]

0        Yes
1         No
2        Yes
3         No
4        Yes
5        Yes
6         No
7        Yes
8        Yes
9        Yes
10       Yes
11        No
12       Yes
13       Yes
14       Yes
15       Yes
16       Yes
17       Yes
18       Yes
19        No
20       Yes
21       Yes
22       Yes
23       Yes
24        No
25       Yes
26       Yes
27       Yes
28       Yes
29        No
30        No
31        No
32        No
33       Yes
34        No
35       Yes
36       Yes
37       Yes
38       Yes
39       Yes
        ...
88843     No
88844    Yes
88845     No
88846    Yes
88847     No
88848    Yes
88849     No
88850     No
88851     No
88852    Yes
88853    Yes
88854    Yes
88855     No
88856     No
88857     No
88858     No
88859     No
88860    Yes
88861     No
88862    Yes
88863    Yes
88864    Yes
88865    Yes
88866    Yes
88867    Yes
88868     No
88869     No
88870    Yes
88871    Yes
88872    Yes
88873     No
88874     No
88875    Yes
88876     No
88877    Yes
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: str

In [17]:
schema_df.columns

Index(['Column', 'QuestionText'], dtype='str')

In [13]:
df.index

RangeIndex(start=0, stop=88883, step=1)

In [14]:
df.set_index("Respondent",inplace=True)

In [18]:
df.isna().sum()

MainBranch                  552
Hobbyist                      0
OpenSourcer                   0
OpenSource                 2041
Employment                 1702
Country                     132
Student                    1869
EdLevel                    2493
UndergradMajor            13269
EduOther                   4623
OrgSize                   17092
DevType                    7548
YearsCode                   945
Age1stCode                 1249
YearsCodePro              14552
CareerSat                 16036
JobSat                    17895
MgrIdiot                  27724
MgrMoney                  27726
MgrWant                   27651
JobSeek                    8328
LastHireDate               9029
LastInt                   21728
FizzBuzz                  17539
JobFactors                 9512
ResumeUpdate              11006
CurrencySymbol            17491
CurrencyDesc              17491
CompTotal                 32938
CompFreq                  25615
ConvertedComp             33060
WorkWeekHrs               24380
WorkPlan                  19969
WorkChallenge             20742
WorkRemote                18599
WorkLoc                   18828
ImpSyn                    17104
CodeRev                   18493
CodeRevHrs                39093
UnitTests                 26215
PurchaseHow               27775
PurchaseWhat              26854
LanguageWorkedWith         1314
LanguageDesireNextYear     4795
DatabaseWorkedWith        12857
DatabaseDesireNextYear    19736
PlatformWorkedWith         8169
PlatformDesireNextYear    11440
WebFrameWorkedWith        23861
WebFrameDesireNextYear    25939
MiscTechWorkedWith        29297
MiscTechDesireNextYear    24372
DevEnviron                 1566
OpSys                      1032
Containers                 3517
BlockchainOrg             40708
BlockchainIs              28718
BetterLife                 2614
ITperson                   1742
OffOn                      2220
SocialMedia                4446
Extraversion               1578
ScreenName                 8397
SOVisit1st                 5006
SOVisitFreq                 620
SOVisitTo                   797
SOFindAnswer               1067
SOTimeSaved                2539
SOHowMuchTime             20505
SOAccount                  1055
SOPartFreq                14191
SOJobs                      817
EntTeams                   1042
SOComm                      752
WelcomeChange              3028
SONewContent              19323
Age                        9673
SurveyLength               1899
SurveyEase                 1802
dtype: int64

In [29]:
schema_df.set_index("Column",inplace=True)

In [30]:
schema_df.sort_index(inplace=True)   # We are just sorted alfhabetıclly use ındex
#ascending=False thıs tıme it sorted begın to reverse alhfabetıclly

In [31]:
schema_df

                                                                                                                                                                                                                                                                                                                                                            QuestionText
Column
Age                                                                                                                                                                                                                                                                         What is your age (in years)? If you prefer not to answer, you may leave this question blank.
Age1stCode                                                                                                                                                                                                                                                   At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scratch project)
BetterLife                                                                                                                                                                                                                                                                                    Do you think people born today will have a better life than their parents?
BlockchainIs                                                                                                                                                                                                                                                                                                        Blockchain / cryptocurrency technology is primarily:
BlockchainOrg                                                                                                                                                                                                                                                                             How is your organization thinking about or implementing blockchain technology?
CareerSat                                                                                                                                                                                                                                                                                                      Overall, how satisfied are you with your career thus far?
CodeRev                                                                                                                                                                                                                                                                                                                         Do you review code as part of your work?
CodeRevHrs                                                                                                                                                                                                                                                                                              On average, how many hours per week do you spend on code review?
CompFreq                                                                                                                                                                                                                                                                                                                Is that compensation weekly, monthly, or yearly?
CompTotal               What is your current total compensation (salary, bonuses, and perks, before taxes and deductions), in `CurrencySymbol`? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent weekly, monthly, or yearly salary. If you prefer not to answer, please leave the box empty.
Containers                                                                                                                                                                                                                                                                                    How do you use containers (Docker, Open Container Initiative (OCI), etc.)?
ConvertedComp                                                                                                                                                                                                                            Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 working months and 50 working weeks.
Country                                                                                                                                                                                                                                                                                                                        In which country do you currently reside?
CurrencyDesc                                                                                                                                                                                                                             Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in.
CurrencySymbol                                                                                                                                                                                                                           Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in.
DatabaseDesireNextYear                                                                    Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year?   (If you both worked with the database and want to continue to do so, please check both boxes in that row.)
DatabaseWorkedWith                                                                        Which of the following database environments have you done extensive development work in over the past year, and which do you want to work in over the next year?   (If you both worked with the database and want to continue to do so, please check both boxes in that row.)
DevEnviron                                                                                                                                                                                                                                                                          Which development environment(s) do you use regularly?  Please check all that apply.
DevType                                                                                                                                                                                                                                                                                               Which of the following describe you? Please select all that apply.
EdLevel                                                                                                                                                                                                                                                               Which of the following best describes the highest level of formal education that you’ve completed?
EduOther                                                                                                                                                                                                                                            Which of the following types of non-degree education have you used or participated in? Please select all that apply.
Employment                                                                                                                                                                                                                                                                                         Which of the following best describes your current employment status?
EntTeams                                                                                                                                                                                                                                                                                   Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
Extraversion                                                                                                                                                                                                                                                                                                             Do you prefer online chat or IRL conversations?
FizzBuzz                                                                                                                                                                                                                                                                                                     Have you ever been asked to solve FizzBuzz in an interview?
Hobbyist                                                                                                                                                                                                                                                                                                                                         Do you code as a hobby?
ITperson                                                                                                                                                                                                                                                                                                                Are you the "IT support person" for your family?
ImpSyn                                                                                                                                                                                                                                                 For the specific work you do, and the years of experience you have, how do you rate your own level of competence?
JobFactors                                                                                                                                                                                         Imagine that you are deciding between two job offers with the same compensation, benefits, and location. Of the following factors, which 3 are MOST important to you?
JobSat                                                                                                                                                                                                                                         How satisfied are you with your current job? (If you work multiple jobs, answer for the one you spend the most hours on.)
JobSeek                                                                                                                                                                                                                                                                                           Which of the following best describes your current job-seeking status?
LanguageDesireNextYear                                              Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year?  (If you both worked with the language and want to continue to do so, please check both boxes in that row.)
LanguageWorkedWith                                                  Which of the following programming, scripting, and markup languages have you done extensive development work in over the past year, and which do you want to work in over the next year?  (If you both worked with the language and want to continue to do so, please check both boxes in that row.)
LastHireDate                                                                                                                                                                                                                                                                                             When was the last time that you took a job with a new employer?
LastInt                                                                                                                                                                                                                                             In your most recent successful job interview (resulting in a job offer), you were asked to... (check all that apply)
MainBranch                                                                                                                                                                                                                                              Which of the following options best describes you today? Here, by "developer" we mean "someone who writes code."
MgrIdiot                                                                                                                                                                                                                                                                                               How confident are you that your manager knows what they’re doing?
MgrMoney                                                                                                                                                                                                                                                                                                Do you believe that you need to be a manager to make more money?
MgrWant                                                                                                                                                                                                                                                                                                          Do you want to become a manager yourself in the future?
MiscTechDesireNextYear                                                   Which of the following other frameworks, libraries, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the technology and want to continue to do so, please check both boxes in that row.)
MiscTechWorkedWith                                                       Which of the following other frameworks, libraries, and tools have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the technology and want to continue to do so, please check both boxes in that row.)
OffOn                                                                                                                                                                                                                                                                                                                        Have you tried turning it off and on again?
OpSys                                                                                                                                                                                                                                                                                                            What is the primary operating system in which you work?
OpenSource                                                                                                                                                                                                                                                                                              How do you feel about the quality of open source software (OSS)?
OpenSourcer                                                                                                                                                                                                                                                                                                                  How often do you contribute to open source?
OrgSize                                                                                                                                                                                                                                                                          Approximately how many people are employed by the company or organization you work for?
PlatformDesireNextYear                                                                                                                                  Which of the following platforms have you done extensive development work for over the past year?   (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)
PlatformWorkedWith                                                                                                                                      Which of the following platforms have you done extensive development work for over the past year?   (If you both developed for the platform and want to continue to do so, please check both boxes in that row.)
PurchaseHow                                                                                                                                                                                                                                                            How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?
PurchaseWhat                                                                                                                                                                                                                                                        What level of influence do you, personally, have over new technology purchases at your organization?
Respondent                                                                                                                                                                                                                                                                                        Randomized respondent ID number (not in order of survey response time)
ResumeUpdate                                                                                                                                                                                                                    Think back to the last time you updated your resumé, CV, or an online profile on a job site. What is the PRIMARY reason that you did so?
SOAccount                                                                                                                                                                                                                                                                                                                          Do you have a Stack Overflow account?
SOComm                                                                                                                                                                                                                                                                                                Do you consider yourself a member of the Stack Overflow community?

In [32]:
high_salary= ( df["ConvertedComp"] > 70000 )

In [34]:
df.loc[high_salary,"ConvertedComp"]

Respondent
6         366420.0
9          95179.0
13         90000.0
16        455352.0
22        103000.0
26        114000.0
29        100000.0
30         90417.0
32       1100000.0
35         80000.0
39        156000.0
44         87996.0
45        175000.0
47        187000.0
57         97389.0
58       2000000.0
60        107000.0
62         87994.0
66        137490.0
70         75000.0
72        110352.0
74        114575.0
77        100000.0
82        143932.0
83        117540.0
95        110000.0
100       229016.0
102      2000000.0
106       160000.0
108       140000.0
110       100000.0
116       103117.0
125       194800.0
127       106000.0
128      1000000.0
131       199450.0
132        83200.0
142       180000.0
143        93951.0
148       135000.0
           ...
88726      89364.0
88733     120000.0
88737      80202.0
88742      95000.0
88748      87789.0
88749      71000.0
88751      91660.0
88754    1000000.0
88758     124000.0
88762      80000.0
88764     120000.0
88767     235080.0
88771     120000.0
88777      79500.0
88778      96558.0
88794     225000.0
88796     105000.0
88799      72912.0
88815    2000000.0
88818    2000000.0
88827     110000.0
88833     204100.0
88834     120000.0
88835     230000.0
88839      95000.0
88842     111000.0
88850     120000.0
88853     110000.0
88855      80000.0
88861      97389.0
88865     120000.0
88867     412464.0
88868     797436.0
88873      72522.0
88874    2000000.0
88876     180000.0
88877    2000000.0
88878     130000.0
88879      82488.0
88882     588012.0
Name: ConvertedComp, Length: 22289, dtype: float64

In [37]:
countries=["United States","United Kingdom","Turkey"]
filt=df["Country"].isin(countries)    #ÖNEMLİ!!!

In [38]:
df.loc[filt,"Country"]

Respondent
1        United Kingdom
4         United States
13        United States
16       United Kingdom
22        United States
23        United States
26        United States
28               Turkey
29        United States
32        United States
35        United States
39        United States
45        United States
46        United States
47        United States
51        United States
53        United States
58        United States
60        United States
61        United States
70        United States
76       United Kingdom
77        United States
80       United Kingdom
82       United Kingdom
88        United States
94       United Kingdom
95        United States
97        United States
102       United States
105       United States
106       United States
108       United States
110       United States
111       United States
117       United States
123              Turkey
126       United States
127       United States
128      United Kingdom
              ...
53011     United States
54777     United States
55003    United Kingdom
55851     United States
55901     United States
56384    United Kingdom
57520     United States
59190     United States
59435    United Kingdom
59455     United States
59604    United Kingdom
61017     United States
62294    United Kingdom
65296     United States
65884    United Kingdom
66914    United Kingdom
67146    United Kingdom
67164     United States
67206     United States
67290     United States
67381    United Kingdom
68208     United States
70197     United States
70955     United States
72325     United States
73695    United Kingdom
74976     United States
77890     United States
77920     United States
78292     United States
78741    United Kingdom
79798    United Kingdom
80116    United Kingdom
82717     United States
82789    United Kingdom
83397     United States
84539    United Kingdom
85642     United States
85961    United Kingdom
88282     United States
Name: Country, Length: 27635, dtype: str

In [42]:
fact=df["LanguageWorkedWith"].str.contains("Java")
fact

Respondent
1         True
2        False
3        False
4        False
5         True
6         True
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14       False
15        True
16        True
17        True
18       False
19        True
20        True
21        True
22        True
23        True
24        True
25        True
26        True
27        True
28        True
29        True
30       False
31       False
32        True
33       False
34        True
35        True
36        True
37        True
38        True
39        True
40       False
         ...
83000    False
83397     True
83511    False
83612    False
83648    False
83709     True
83777    False
83786     True
83800    False
83862     True
84299     True
84539     True
85182    False
85208    False
85396    False
85538    False
85642    False
85738    False
85744    False
85955    False
85961    False
86012     True
86566    False
86638    False
86806    False
86980    False
86999    False
87352     True
87386     True
87739     True
88062    False
88076    False
88182     True
88212     True
88282     True
88377     True
88601    False
88802    False
88816    False
88863     True
Name: LanguageWorkedWith, Length: 88883, dtype: bool

In [43]:
df.loc[fact,"LanguageWorkedWith"]

Respondent
1                                                                                                                                                                         HTML/CSS;Java;JavaScript;Python
5                                                                                                                                                             C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
6                                                                                                                                                                                              Java;R;SQL
7                                                                                                                                                                                     HTML/CSS;JavaScript
8                                                                                                                                         Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;Python;SQL
9                                                                                                      Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;Python;Ruby;Rust;SQL;TypeScript;WebAssembly;Other(s):
10                                                                                                                                                                          C#;Go;JavaScript;Python;R;SQL
12                                                                                                                                                       Bash/Shell/PowerShell;HTML/CSS;Java;Python;R;SQL
13                                                                                                                                           Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL;TypeScript
15                                                                                                                                  Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;PHP;SQL
16                                                                                                                                            Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;TypeScript;VBA
17                                                                                                                                                   Bash/Shell/PowerShell;HTML/CSS;JavaScript;TypeScript
19                                                                                                                                                             C#;HTML/CSS;Java;JavaScript;SQL;TypeScript
20                                                                                                                                     Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScript;PHP;Python;R;SQL
21                                                                                                                   Assembly;Bash/Shell/PowerShell;C;C++;Go;Java;JavaScript;Kotlin;Python;Rust;SQL;Swift
22                                                                                                                               Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;Python;Ruby;SQL;TypeScript
23                                                                                                                                              Bash/Shell/PowerShell;HTML/CSS;JavaScript;Python;Ruby;SQL
24                                                                                                                                                                     HTML/CSS;JavaScript;PHP;TypeScript
25                                                                                                                                                                 HTML/CSS;JavaScript;PHP;SQL;TypeScript
26                                                                                                              Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScript;PHP;Python;Ruby;SQL;Swift;TypeScript;VBA
27                                                                                                                                                              C++;JavaScript;Python;Ruby;SQL;TypeScript
28                                                                                                                                                                                  JavaScript;TypeScript
29                                                                                                                                                                   Bash/Shell/PowerShell;JavaScript;SQL
32                                                                                                                                                   Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;Python
34                                                                                                                                                                                    HTML/CSS;JavaScript
35                                                                                                                                                                                    HTML/CSS;JavaScript
36                                                                                                                                                                                     Java;Kotlin;Python
37                                                                                                                                                      Bash/Shell/PowerShell;JavaScript;Python;Other(s):
38                                                                                                                                                                             C#;HTML/CSS;JavaScript;SQL
39                                                                                                                                                                           C#;JavaScript;SQL;TypeScript
41                                                                                                                                               Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;SQL
42                                                                                                                                                                     HTML/CSS;JavaScript;PHP;TypeScript
43                                                                                                                                                        C++;C#;HTML/CSS;Java;JavaScript;Objective-C;SQL
44                                                                                                                           Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScript;SQL;TypeScript;WebAssembly
46                                                                                                                                Bash/Shell/PowerShell;C;C#;HTML/CSS;JavaScript;PHP;Python;SQL;Other(s):
47                                                                                                                                                                                          Java;PHP;Ruby
49                                                                                                                               Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;PHP;Python;SQL;TypeScript
50                                                                                                                                    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;PHP;Python;SQL
51                                                                                                                                 Bash/Shell/PowerShell;C++;HTML/CSS;Java;JavaScript;Python;R;TypeScript
52                                                                                           Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;HTML/CSS;Java;JavaScript;Kotlin;Python;Ruby;Rust;SQL;TypeScript
                                                                                                       ...
68501                                                                                                                                                               Java;JavaScript;Kotlin;SQL;TypeScript
68525                                                                                                                                                    Bash/Shell/PowerShell;HTML/CSS;JavaScript;Python
69190                                                                                                                                                                         HTML/CSS;JavaScript;PHP;SQL
69366                                                                                                                                                                              JavaScript;Python;Ruby
70630                                                                                                                                      Bash/Shell/PowerShell;C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
70955                                                                                                                                                                                 HTML/CSS;JavaScript
70985                                                                                                                                                                            HTML/CSS;Java;Python;SQL
71160                                                                                                                                     Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;Python;SQL
71874    Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojure;Dart;Elixir;Erlang;F#;Go;HTML/CSS;Java;JavaScript;Kotlin;Objective-C;PHP;Python;R;Ruby;Rust;Scala;SQL;Swift;TypeScript;VBA;WebAssembly;Other(s):
72325                                                                                                                                                                    HTML/CSS;JavaScript;Python;Swift
72492                                                                                                                      Bash/Shell/PowerShell;Elixir;Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript
75103                                                                                                                                                                                            Java;VBA
75842                                                                                                                                                                                     Java;JavaScript
75974                                                                                                                                          Go;HTML/CSS;Java;JavaScript;Kotlin;Python;Swift;TypeScript
76822                                                                                                                                                  Assembly;C++;HTML/CSS;JavaScript;PHP;SQL;Other(s):
77920                                                                                                                                          Bash/Shell/PowerShell;C;C++;HTML/CSS;JavaScript;TypeScript
77968                                                                                                                                                                          Java;Python;SQL;TypeScript
78741    Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojure;Dart;Elixir;Erlang;F#;Go;HTML/CSS;Java;JavaScript;Kotlin;Objective-C;PHP;Python;R;Ruby;Rust;Scala;SQL;Swift;TypeScript;VBA;WebAssembly;Other(s):
79354                                                                                                                                                                          Java;JavaScript;Kotlin;SQL
79798                                                                                                                                                                          HTML/CSS;JavaScript;Python
80116                                                                                                                                                                                  HTML/CSS;Java;Ruby
80319                                                                                                                                              Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;PHP;SQL
81922                                                                                                                                                                                                Java
81994                                                                                                                                                                              Erlang;Java;Python;SQL
82007                                                                                                                                                         Assembly;Java;JavaScript;Objective-C;Python
83397                                                                                                                                                                      HTML/CSS;JavaScript;Python;SQL
83709                                                                                                                                               Bash/Shell/PowerShell;HTML/CSS;JavaScript;Python;Ruby
83786                                                                                                                                                               HTML/CSS;JavaScript;Kotlin;TypeScript
83862                                                                                                                                         Assembly;C;C++;HTML/CSS;Java;JavaScript;Objective-C;PHP;SQL
84299                                                                                                                                                    HTML/CSS;Java;JavaScript;Python;Swift;TypeScript
84539                                                                                                                                     Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;Python;SQL
86012                                                                                                                                                       Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript
87352                                                                                                                                                                                          C;C++;Java
87386                                                                                                                      Assembly;Bash/Shell/PowerShell;C;C#;HTML/CSS;Java;JavaScript;PHP;SQL;Other(s):
87739                                                                                                                                                            C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88182                                                                                                                                                                            HTML/CSS;Java;JavaScript
88212                                                                                                                                                                          HTML/CSS;JavaScript;Python
88282                                                                                                                                            Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;WebAssembly
88377                                                                                                                                                                       HTML/CSS;JavaScript;Other(s):
88863                                                                                                                                        Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;PHP;SQL;Swift
Name: LanguageWorkedWith, Length: 70113, dtype: str

In [44]:
df.rename(columns={"ConvertedComp" : "SalaryUSD"},inplace=True)
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Courses on technologies you're interested in,14.0,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,"Financial performance or funding status of the company or organization;Specific department or team I'd be working on;Languages, frameworks, and other technologies I'd be working with","Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,19.0,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time or a flexible schedule",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company culture;Opportunities for professional development",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,22.0,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software","10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Developer, mobile",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Interview with people in senior / management roles",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working with;Flex time or a flexible schedule",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments (parenting, school work, hobbies, etc.)",A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Appropriate in length,Easy
6,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,"Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course",NaN,"Data or business analyst;Data scientist or machine learning specialist;Database administrator;Engineer, data",13,15,3,Very satisfied,Slightly satisfied,Very confident,No,Yes,I am not interested in new job opportunities,1-2 years ago,Write any code;Complete a take-home project;Interview with people in senior / management roles,No,Financial performance or funding status of the company or organization;Opportunities for professional development;How widely used or impactful my work output would be,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",CAD,Canadian dollar,40000.0,Monthly,366420.0,15.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,A few days each month,Home,A little above average,No,NaN,"Yes, it's not part of our process but the developers do it on their own",Not sure,I have little or no influence,Java;R;SQL,Python;Scala;SQL,MongoDB;PostgreSQL,PostgreSQL,Android;Google Cloud Platform;Linux;Windows,Android;Google Cloud Platform;Linux;Windows,NaN,NaN,Hadoop,Hadoop;Pandas;TensorFlow;Unity 3D,Android Studio;Eclipse;PyCharm;RStudio;Visual Studio Code,Windows,I do not use containers,Not at all,NaN,No,Yes,No,YouTube,In real life (in person),Login,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Overflow,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Too long,Neither easy nor difficult
7,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,"Independent contractor, freelancer, or self-employed",Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, electrical, mechanical)","Taught yourself a new language, framework, or tool without taking a formal course","Just me - I am a freelancer, sole proprietor, etc.","Designer;Developer, front-end",6,17,4,Slightly satisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",NA - I am an independent contractor or self employed,Write any code,No,Remote work options;Opportunities for professional development;Flex time or a flexible schedule,NaN,USD,United States dollar,NaN,NaN,NaN,32.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Being tasked with non-development work;Distracting work environment;Non-work commitments (parenting, school work, hobbies, etc.)",All or almost all the time (I'm full-time remote),"Other place, such as a coworking space or cafe",Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,HTML/CSS;JavaScript,HTML/CSS;JavaScript,NaN,NaN,MacOS;Windows,MacOS;Windows,React.js,React.js,NaN,NaN,PHPStorm,Windows,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,No,YouTube,NaN,NaN,2014,Daily or almost daily,Find answers to specific questions,3-5 times per week,NaN,NaN,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Neutral,A lot more welcome now than last year,NaN,42.0,Appropriate in length,Neither easy nor difficult
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taught yourself a new language, framework, or tool without taking a formal course;Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder);Contributed to open source software",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;JavaScript;Python;SQL,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;Python;SQL;WebAssembly,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;Redis;SQLite,Cassandra;DynamoDB;Elasticsearch;Firebase;MongoDB;MySQL;PostgreSQL;Redis,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platform;IBM Cloud or Watson;Kubernetes;Linux;MacOS;Raspberry Pi;Slack,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Pandas;Puppet;React Native;TensorFlow;Torch/PyTorch;Unreal Engine,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual Studio Code,Linux-based,"Development;Testing;Production;Outside of work, for personal projects",NaN,Useful across many domains and could change many aspects of our lives,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Contribute to a library of information,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,24.0,Appropriate in length,Neither easy nor difficult
9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software is about the same,Employed full-time,New Zealand,No,Some college/university study without earning a degree,"Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Participated in a full-time developer training program or bootcamp;Taken a part-time in-person course in programming or software development;Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course;Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder);Contributed to open source software",10 to 19 employees,"Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, QA or test;DevOps specialist",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,Write any code;Interview with people in peer roles;Interview with people in senior / management roles,Yes,Financial performance or funding status of the company or organization;Office environment or company culture;How widely used or impactful my work output would be,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Being tasked with non-development work;Inadequate access to necessary tools;Not enough people for the workload,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the developers do it on their own",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;Python;Ruby;Rust;SQL;TypeScript;WebAssembly;Other(s):,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ruby;Rust;SQL;TypeScript;WebAssembly;Other(s):,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute to a library of information,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Appropriate in length,Neither easy nor difficult

In [17]:
df["Hobbyist"]=df["Hobbyist"].map({"Yes":True,"No":False})
df["Hobbyist"]

0         True
1        False
2         True
3        False
4         True
5         True
6        False
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14        True
15        True
16        True
17        True
18        True
19       False
20        True
21        True
22        True
23        True
24       False
25        True
26        True
27        True
28        True
29       False
30       False
31       False
32       False
33        True
34       False
35        True
36        True
37        True
38        True
39        True
         ...
88843    False
88844     True
88845    False
88846     True
88847    False
88848     True
88849    False
88850    False
88851    False
88852     True
88853     True
88854     True
88855    False
88856    False
88857    False
88858    False
88859    False
88860     True
88861    False
88862     True
88863     True
88864     True
88865     True
88866     True
88867     True
88868    False
88869    False
88870     True
88871     True
88872     True
88873    False
88874    False
88875     True
88876    False
88877     True
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: bool

In [32]:
df.sort_values(by=["Country","ConvertedComp"],ascending=[True,False],inplace=True)

In [33]:
df[["Country","ConvertedComp"]].head(100)

           Country  ConvertedComp
62723  Afghanistan      1000000.0
50172  Afghanistan       153216.0
39018  Afghanistan        19152.0
58082  Afghanistan        17556.0
7056   Afghanistan        14364.0
22327  Afghanistan         7980.0
48122  Afghanistan         4464.0
10697  Afghanistan         3996.0
8112   Afghanistan         1596.0
29560  Afghanistan         1116.0
28470  Afghanistan            0.0
719    Afghanistan            0.0
85185  Afghanistan            NaN
50437  Afghanistan            NaN
88340  Afghanistan            NaN
88735  Afghanistan            NaN
6391   Afghanistan            NaN
39754  Afghanistan            NaN
88181  Afghanistan            NaN
62124  Afghanistan            NaN
49377  Afghanistan            NaN
32971  Afghanistan            NaN
60559  Afghanistan            NaN
85827  Afghanistan            NaN
88033  Afghanistan            NaN
26189  Afghanistan            NaN
86394  Afghanistan            NaN
85293  Afghanistan            NaN
7323   Afghanistan            NaN
86551  Afghanistan            NaN
58390  Afghanistan            NaN
73920  Afghanistan            NaN
28877  Afghanistan            NaN
51525  Afghanistan            NaN
45562  Afghanistan            NaN
46807  Afghanistan            NaN
44123  Afghanistan            NaN
80423  Afghanistan            NaN
59184  Afghanistan            NaN
60185  Afghanistan            NaN
...            ...            ...
43601      Albania        20628.0
12208      Albania        18768.0
62229      Albania        17664.0
18193      Albania        13800.0
62511      Albania        13752.0
28995      Albania        13752.0
84729      Albania        12804.0
21584      Albania        11040.0
1946       Albania        11040.0
13322      Albania        10596.0
24955      Albania         9936.0
27476      Albania         9624.0
80012      Albania         9384.0
35805      Albania         8832.0
15910      Albania         8832.0
69716      Albania         7728.0
76073      Albania         7728.0
15295      Albania         7728.0
18766      Albania         7728.0
73036      Albania         7728.0
40574      Albania         7728.0
64815      Albania         7176.0
58394      Albania         7176.0
55994      Albania         6624.0
11496      Albania         6624.0
69857      Albania         6624.0
33385      Albania         5520.0
33999      Albania         5496.0
55041      Albania         5496.0
78326      Albania         4968.0
76755      Albania         4416.0
25440      Albania         4416.0
59980      Albania         3864.0
70280      Albania         1320.0
57057      Albania            NaN
49431      Albania            NaN
41344      Albania            NaN
33177      Albania            NaN
10886      Albania            NaN
55196      Albania            NaN

[100 rows x 2 columns]

In [20]:
df["ConvertedComp"].nlargest(10)

57      2000000.0
101     2000000.0
164     2000000.0
434     2000000.0
450     2000000.0
489     2000000.0
537     2000000.0
767     2000000.0
786     2000000.0
1228    2000000.0
Name: ConvertedComp, dtype: float64

In [46]:
df.nlargest(1,["SalaryUSD"])

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
58,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than proprietary / closed source software",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Received on-the-job training in software development;Taught yourself a new language, framework, or tool without taking a formal course",NaN,"Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, mobile",28,19,23,Very satisfied,Very satisfied,Very confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,NaN,Yes,Office environment or company culture;Remote work options;Flex time or a flexible schedule,Re-entry into the workforce,USD,United States dollar,113000.0,Weekly,2000000.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,"Being tasked with non-development work;Non-work commitments (parenting, school work, hobbies, etc.);Time spent commuting","Less than half the time, but at least one day each week",Home,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers and management have nearly equal input into purchasing new technology,I have a great deal of influence,C#;Java;SQL,C#;F#;Java;Kotlin;SQL,Microsoft SQL Server;Oracle;SQLite,Microsoft SQL Server;Oracle;SQLite,Android;Windows,Android;Raspberry Pi;Windows,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET,Hadoop;.NET;.NET Core;Node.js;Puppet;Xamarin,Android Studio;Visual Studio,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,I don't use social media,In real life (in person),Login,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,47.0,NaN,Easy

In [47]:
df.describe()

          CompTotal     SalaryUSD   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04  5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11  1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13  2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00  0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04  2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04  5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05  1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16  2.000000e+06   4850.000000     99.000000     99.000000

In [48]:
df["SocialMedia"].value_counts(normalize=True)

SocialMedia
Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: proportion, dtype: float64

In [29]:
df["Country"].value_counts()

Country
United States                            20949
India                                     9061
Germany                                   5866
United Kingdom                            5737
Canada                                    3395
France                                    2391
Brazil                                    1948
Poland                                    1922
Australia                                 1903
Netherlands                               1852
Russian Federation                        1694
Spain                                     1604
Italy                                     1576
Sweden                                    1274
Switzerland                                978
Israel                                     952
Turkey                                     949
Pakistan                                   923
Ukraine                                    868
Austria                                    839
Czech Republic                             764
Romania                                    760
Iran                                       738
Belgium                                    727
China                                      664
Bulgaria                                   659
Mexico                                     642
South Africa                               627
Denmark                                    617
Bangladesh                                 605
Norway                                     574
Greece                                     556
Argentina                                  553
Finland                                    546
Portugal                                   525
New Zealand                                524
Nigeria                                    522
Hungary                                    513
Indonesia                                  507
Ireland                                    501
                                         ...
Fiji                                         5
Haiti                                        5
Benin                                        5
Namibia                                      5
Angola                                       5
Botswana                                     5
Monaco                                       4
Togo                                         4
Burkina Faso                                 4
Cape Verde                                   3
Burundi                                      3
Belize                                       3
Mali                                         3
Guyana                                       3
Liechtenstein                                3
Lao People's Democratic Republic             3
Guinea                                       3
Democratic People's Republic of Korea        3
Barbados                                     3
Lesotho                                      3
Bahamas                                      3
Sierra Leone                                 2
Gabon                                        2
Djibouti                                     2
Seychelles                                   2
Malawi                                       2
Liberia                                      2
Bhutan                                       2
San Marino                                   2
Brunei Darussalam                            1
North Korea                                  1
Timor-Leste                                  1
Tonga                                        1
Niger                                        1
Dominica                                     1
Papua New Guinea                             1
Saint Kitts and Nevis                        1
Saint Vincent and the Grenadines             1
Sao Tome and Principe                        1
Chad                                         1
Name: count, Length: 179, dtype: int64

In [57]:
country_grp=df.groupby("Country")

In [58]:
country_grp.get_group("Turkey").head(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
27,28,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance, marketing)","Taken an online course in programming or software development (e.g. a MOOC);Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software",2-9 employees,"Designer;Developer, front-end;Developer, full-stack",10,35,5,Very satisfied,Very satisfied,Very confident,No,No,"I’m not actively looking, but I am open to new opportunities",More than 4 years ago,Complete a take-home project,No,Financial performance or funding status of the company or organization;Remote work options;Flex time or a flexible schedule,"My job status changed (promotion, new job, etc.)",TRY,Turkish lira,NaN,Monthly,NaN,40.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",NaN,All or almost all the time (I'm full-time remote),Home,Far above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Developers and management have nearly equal input into purchasing new technology,I have some influence,JavaScript;TypeScript,JavaScript,MariaDB;MongoDB,MariaDB;MongoDB,NaN,NaN,React.js;Vue.js,Vue.js,Node.js,Node.js,Visual Studio Code,Windows,Development;Testing;Production,Not at all,NaN,No,SIGH,Yes,Instagram,Neither,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,NaN,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","No, not at all",NaN,NaN,NaN,NaN,NaN
122,123,I am a developer by profession,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, electrical, mechanical)","Taken an online course in programming or software development (e.g. a MOOC);Participated in a full-time developer training program or bootcamp;Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder)","1,000 to 4,999 employees","Developer, back-end;Developer, front-end;Developer, full-stack",6,19,3,Very satisfied,Very satisfied,Somewhat confident,Yes,Not sure,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Complete a take-home project;Solve a brain-teaser style puzzle;Interview with people in peer roles;Interview with people in senior / management roles",Yes,Office environment or company culture;How widely used or impactful my work output would be;Flex time or a flexible schedule,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",TRY,Turkish lira,8000.0,Monthly,18432.0,45.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Meetings;Non-work commitments (parenting, school work, hobbies, etc.);Toxic work environment",Less than once per month / Never,Home,A little above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers typically have the most influence on purchasing new technology,I have some influence,HTML/CSS;JavaScript;TypeScript,JavaScript;Python;TypeScript,NaN,Couchbase;Redis,NaN,Arduino;Docker;Kubernetes;Raspberry Pi;Slack,Angular/Angular.js;ASP.NET;jQuery;React.js;Vue.js,Express;React.js;Vue.js,NaN,Node.js;React Native;TensorFlow,Visual Studio Code,MacOS,"Production;Outside of work, for personal projects",Non-currency applications of blockchain,NaN,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2014,Multiple times per day,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Contribute to a library of information,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,24.0,Too long,Easy

In [59]:
country_grp["SocialMedia"].value_counts(normalize=True).loc["United States"]

SocialMedia
Reddit                      0.284346
Twitter                     0.173002
Facebook                    0.141874
YouTube                     0.122867
I don't use social media    0.092338
Instagram                   0.082410
LinkedIn                    0.050883
WhatsApp                    0.030380
Snapchat                    0.016263
WeChat 微信                   0.004639
VK ВКонта́кте               0.000449
Weibo 新浪微博                  0.000399
Hello                       0.000100
Youku Tudou 优酷              0.000050
Name: proportion, dtype: float64

In [60]:
country_grp["ConvertedComp"].median().loc["Turkey"]

np.float64(17280.0)

In [98]:
country_grp["ConvertedComp"].agg(["median","mean"])

                                             median           mean
Country
Afghanistan                                  6222.0  101953.333333
Albania                                     10818.0   21833.700000
Algeria                                      7878.0   34924.047619
Andorra                                    160931.0  160931.000000
Angola                                       7764.0    7764.000000
Antigua and Barbuda                             NaN            NaN
Argentina                                   17760.0   29467.265306
Armenia                                     19692.0   24691.733333
Australia                                   79783.0  171541.116279
Austria                                     51559.0   83955.639604
Azerbaijan                                  15858.0   15785.750000
Bahamas                                         NaN            NaN
Bahrain                                     15912.0   23934.000000
Bangladesh                                   8764.0   21249.652000
Barbados                                    21000.0   21000.000000
Belarus                                     24000.0   29442.330645
Belgium                                     48120.0   73185.564655
Belize                                          NaN            NaN
Benin                                           NaN            NaN
Bhutan                                          NaN            NaN
Bolivia                                     13020.0   17977.360000
Bosnia and Herzegovina                      18360.0   24996.283333
Botswana                                    38410.0   40994.000000
Brazil                                      18036.0   32623.570000
Brunei Darussalam                            6096.0    6096.000000
Bulgaria                                    28080.0   42642.419355
Burkina Faso                                 8388.0    8388.000000
Burundi                                      3606.0    3606.000000
Cambodia                                    10420.0   31957.000000
Cameroon                                     6288.0   24194.913043
Canada                                      68705.0  134018.564909
Cape Verde                                      NaN            NaN
Chad                                         6288.0    6288.000000
Chile                                       27528.0   40438.909722
China                                       28464.0   57430.421053
Colombia                                    15528.0   24502.876190
Congo, Republic of the...                   18000.0   16852.000000
Costa Rica                                  38400.0   40982.647059
Croatia                                     24108.0   45305.660714
Cuba                                         3666.0   10920.555556
...                                             ...            ...
Serbia                                      24672.0   34142.277273
Seychelles                                  61308.0   61308.000000
Sierra Leone                                    NaN            NaN
Singapore                                   57758.5  120621.506410
Slovakia                                    32658.0   43292.906667
Slovenia                                    34368.0   55717.803922
Somalia                                      7800.0   30999.000000
South Africa                                38354.0   63550.602871
South Korea                                 40950.5   79716.100000
Spain                                       40101.0   88724.357262
Sri Lanka                                    7476.0   13568.012121
Sudan                                        2016.0    5195.333333
Swaziland                                   62371.0  242607.500000
Sweden                                      56004.0   76865.636163
Switzerland                                 95440.0  172675.602679
Syrian Arab Republic                         2742.0    3562.500000
Taiwan                                      27954.0   40364.712963
Tajikistan                                   4902.0    4902.000000
Thailand                                    30672.0   48379.436893
The former Yugoslav Republic of Macedonia   21996.0   40389.451613
Timor-Leste                                229500.0  229500.000000
Togo                                         4188.0    4188.000000
Tonga                                           NaN            NaN
Trinidad and Tobago                         27828.0   50346.777778
Tunisia                                      6468.0   10130.129630
Turkey                                      17280.0   25133.222664
Turkmenistan                                27348.0   46449.333333
Uganda                                       5490.0   37974.352941
Ukraine                                     26940.0   32698.136531
United Arab Emirates                        49008.0   53545.659091
United Kingdom                              68041.0  166182.499504
United Republic of Tanzania                  5192.0   34691.117647
United States                              110000.0  249546.254589
Uruguay                                     33850.0   53862.571429
Uzbekistan                                   7176.0   18304.142857
Venezuela, Bolivarian Republic of...         6384.0   14581.627907
Viet Nam                                    11892.0   17233.436782
Yemen                                       11940.0   16909.166667
Zambia                                       5040.0   10075.375000
Zimbabwe                                    19200.0   34046.666667

[179 rows x 2 columns]

In [83]:
filt=df["Country"]=="India"
df.loc[filt,"LanguageWorkedWith"].str.contains("Python").sum()

np.int64(3105)

In [77]:
country_grp["LanguageWorkedWith"].str.contains("Python").sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [110]:
country_grp["LanguageWorkedWith"].apply(lambda x :x.str.contains("Python").sum())

Country
Afghanistan                                      8
Albania                                         23
Algeria                                         40
Andorra                                          0
Angola                                           2
Antigua and Barbuda                              0
Argentina                                      191
Armenia                                         28
Australia                                      790
Austria                                        338
Azerbaijan                                      17
Bahamas                                          2
Bahrain                                          4
Bangladesh                                     204
Barbados                                         1
Belarus                                         69
Belgium                                        296
Belize                                           1
Benin                                            3
Bhutan                                           1
Bolivia                                         11
Bosnia and Herzegovina                          29
Botswana                                         1
Brazil                                         767
Brunei Darussalam                                0
Bulgaria                                       181
Burkina Faso                                     0
Burundi                                          1
Cambodia                                         9
Cameroon                                        16
Canada                                        1558
Cape Verde                                       0
Chad                                             0
Chile                                          102
China                                          297
Colombia                                       108
Congo, Republic of the...                        4
Costa Rica                                      30
Croatia                                         87
Cuba                                            16
                                             ...
Serbia                                         117
Seychelles                                       1
Sierra Leone                                     1
Singapore                                      139
Slovakia                                       101
Slovenia                                       119
Somalia                                          3
South Africa                                   202
South Korea                                     80
Spain                                          641
Sri Lanka                                      137
Sudan                                           16
Swaziland                                        2
Sweden                                         496
Switzerland                                    460
Syrian Arab Republic                             7
Taiwan                                          88
Tajikistan                                       0
Thailand                                        92
The former Yugoslav Republic of Macedonia        8
Timor-Leste                                      1
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              5
Tunisia                                         40
Turkey                                         371
Turkmenistan                                     6
Uganda                                          47
Ukraine                                        246
United Arab Emirates                            49
United Kingdom                                2384
United Republic of Tanzania                     15
United States                                10083
Uruguay                                         36
Uzbekistan                                      14
Venezuela, Bolivarian Republic of...            28
Viet Nam                                        78
Yemen                                            3
Zambia                                           4
Zimbabwe                                        14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [158]:
country_grp["LanguageWorkedWith"].apply(lambda x: x.str.contains("Python", na=False).mean())

Country
Afghanistan                                  0.181818
Albania                                      0.267442
Algeria                                      0.298507
Andorra                                      0.000000
Angola                                       0.400000
Antigua and Barbuda                          0.000000
Argentina                                    0.345389
Armenia                                      0.325581
Australia                                    0.415134
Austria                                      0.402861
Azerbaijan                                   0.346939
Bahamas                                      0.666667
Bahrain                                      0.222222
Bangladesh                                   0.337190
Barbados                                     0.333333
Belarus                                      0.341584
Belgium                                      0.407153
Belize                                       0.333333
Benin                                        0.600000
Bhutan                                       0.500000
Bolivia                                      0.305556
Bosnia and Herzegovina                       0.268519
Botswana                                     0.200000
Brazil                                       0.393737
Brunei Darussalam                            0.000000
Bulgaria                                     0.274659
Burkina Faso                                 0.000000
Burundi                                      0.333333
Cambodia                                     0.300000
Cameroon                                     0.313725
Canada                                       0.458910
Cape Verde                                   0.000000
Chad                                         0.000000
Chile                                        0.495146
China                                        0.447289
Colombia                                     0.345048
Congo, Republic of the...                    0.571429
Costa Rica                                   0.357143
Croatia                                      0.334615
Cuba                                         0.533333
                                               ...
Serbia                                       0.291045
Seychelles                                   0.500000
Sierra Leone                                 0.500000
Singapore                                    0.458746
Slovakia                                     0.388462
Slovenia                                     0.399329
Somalia                                      0.230769
South Africa                                 0.322169
South Korea                                  0.500000
Spain                                        0.399626
Sri Lanka                                    0.368280
Sudan                                        0.380952
Swaziland                                    0.250000
Sweden                                       0.389325
Switzerland                                  0.470348
Syrian Arab Republic                         0.241379
Taiwan                                       0.470588
Tajikistan                                   0.000000
Thailand                                     0.429907
The former Yugoslav Republic of Macedonia    0.148148
Timor-Leste                                  1.000000
Togo                                         0.250000
Tonga                                        0.000000
Trinidad and Tobago                          0.263158
Tunisia                                      0.307692
Turkey                                       0.390938
Turkmenistan                                 0.857143
Uganda                                       0.652778
Ukraine                                      0.283410
United Arab Emirates                         0.310127
United Kingdom                               0.415548
United Republic of Tanzania                  0.468750
United States                                0.481312
Uruguay                                      0.324324
Uzbekistan                                   0.358974
Venezuela, Bolivarian Republic of...         0.318182
Viet Nam                                     0.337662
Yemen                                        0.157895
Zambia                                       0.333333
Zimbabwe                                     0.358974
Name: LanguageWorkedWith, Length: 179, dtype: float64

In [308]:
country_grp=df.groupby("Country")

In [318]:
eachCountryKnowPython=country_grp["LanguageWorkedWith"].apply(lambda x:x.str.contains("Python").sum())

Country
Afghanistan                                      8
Albania                                         23
Algeria                                         40
Andorra                                          0
Angola                                           2
Antigua and Barbuda                              0
Argentina                                      191
Armenia                                         28
Australia                                      790
Austria                                        338
Azerbaijan                                      17
Bahamas                                          2
Bahrain                                          4
Bangladesh                                     204
Barbados                                         1
Belarus                                         69
Belgium                                        296
Belize                                           1
Benin                                            3
Bhutan                                           1
Bolivia                                         11
Bosnia and Herzegovina                          29
Botswana                                         1
Brazil                                         767
Brunei Darussalam                                0
Bulgaria                                       181
Burkina Faso                                     0
Burundi                                          1
Cambodia                                         9
Cameroon                                        16
Canada                                        1558
Cape Verde                                       0
Chad                                             0
Chile                                          102
China                                          297
Colombia                                       108
Congo, Republic of the...                        4
Costa Rica                                      30
Croatia                                         87
Cuba                                            16
                                             ...
Serbia                                         117
Seychelles                                       1
Sierra Leone                                     1
Singapore                                      139
Slovakia                                       101
Slovenia                                       119
Somalia                                          3
South Africa                                   202
South Korea                                     80
Spain                                          641
Sri Lanka                                      137
Sudan                                           16
Swaziland                                        2
Sweden                                         496
Switzerland                                    460
Syrian Arab Republic                             7
Taiwan                                          88
Tajikistan                                       0
Thailand                                        92
The former Yugoslav Republic of Macedonia        8
Timor-Leste                                      1
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              5
Tunisia                                         40
Turkey                                         371
Turkmenistan                                     6
Uganda                                          47
Ukraine                                        246
United Arab Emirates                            49
United Kingdom                                2384
United Republic of Tanzania                     15
United States                                10083
Uruguay                                         36
Uzbekistan                                      14
Venezuela, Bolivarian Republic of...            28
Viet Nam                                        78
Yemen                                            3
Zambia                                           4
Zimbabwe                                        14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [311]:
AllPeopleEachCountry=df["Country"].value_counts()

In [312]:
table=pd.concat([AllPeopleEachCountry,eachCountryKnowPython],axis="columns")
table

                                       count  LanguageWorkedWith
Country
United States                          20949               10083
India                                   9061                3105
Germany                                 5866                2451
United Kingdom                          5737                2384
Canada                                  3395                1558
France                                  2391                1054
Brazil                                  1948                 767
Poland                                  1922                 751
Australia                               1903                 790
Netherlands                             1852                 767
Russian Federation                      1694                 708
Spain                                   1604                 641
Italy                                   1576                 625
Sweden                                  1274                 496
Switzerland                              978                 460
Israel                                   952                 457
Turkey                                   949                 371
Pakistan                                 923                 251
Ukraine                                  868                 246
Austria                                  839                 338
Czech Republic                           764                 285
Romania                                  760                 253
Iran                                     738                 268
Belgium                                  727                 296
China                                    664                 297
Bulgaria                                 659                 181
Mexico                                   642                 245
South Africa                             627                 202
Denmark                                  617                 246
Bangladesh                               605                 204
Norway                                   574                 232
Greece                                   556                 226
Argentina                                553                 191
Finland                                  546                 266
Portugal                                 525                 182
New Zealand                              524                 236
Nigeria                                  522                 152
Hungary                                  513                 191
Indonesia                                507                 148
Ireland                                  501                 209
...                                      ...                 ...
Fiji                                       5                   1
Haiti                                      5                   3
Benin                                      5                   3
Namibia                                    5                   3
Angola                                     5                   2
Botswana                                   5                   1
Monaco                                     4                   2
Togo                                       4                   1
Burkina Faso                               4                   0
Cape Verde                                 3                   0
Burundi                                    3                   1
Belize                                     3                   1
Mali                                       3                   1
Guyana                                     3                   2
Liechtenstein                              3                   1
Lao People's Democratic Republic           3                   0
Guinea                                     3                   2
Democratic People's Republic of Korea      3                   1
Barbados                                   3                   1
Lesotho                                    3                   1
Bahamas                                    3                   2
Sierra Leone                               2                   1
Gabon                                      2                   0
Djibouti                                   2                   0
Seychelles                                 2                   1
Malawi                                     2                   0
Liberia                                    2                   0
Bhutan                                     2                   1
San Marino                                 2                   1
Brunei Darussalam                          1                   0
North Korea                                1                   0
Timor-Leste                                1                   1
Tonga                                      1                   0
Niger                                      1                   1
Dominica                                   1                   1
Papua New Guinea                           1                   0
Saint Kitts and Nevis                      1                   0
Saint Vincent and the Grenadines           1                   0
Sao Tome and Principe                      1                   1
Chad                                       1                   0

[179 rows x 2 columns]

In [313]:
table.rename(columns={"count":"AllPeopleEachCountry" ,  "LanguageWorkedWith" :"UserPython"},inplace=True)
table

                                       AllPeopleEachCountry  UserPython
Country
United States                                         20949       10083
India                                                  9061        3105
Germany                                                5866        2451
United Kingdom                                         5737        2384
Canada                                                 3395        1558
France                                                 2391        1054
Brazil                                                 1948         767
Poland                                                 1922         751
Australia                                              1903         790
Netherlands                                            1852         767
Russian Federation                                     1694         708
Spain                                                  1604         641
Italy                                                  1576         625
Sweden                                                 1274         496
Switzerland                                             978         460
Israel                                                  952         457
Turkey                                                  949         371
Pakistan                                                923         251
Ukraine                                                 868         246
Austria                                                 839         338
Czech Republic                                          764         285
Romania                                                 760         253
Iran                                                    738         268
Belgium                                                 727         296
China                                                   664         297
Bulgaria                                                659         181
Mexico                                                  642         245
South Africa                                            627         202
Denmark                                                 617         246
Bangladesh                                              605         204
Norway                                                  574         232
Greece                                                  556         226
Argentina                                               553         191
Finland                                                 546         266
Portugal                                                525         182
New Zealand                                             524         236
Nigeria                                                 522         152
Hungary                                                 513         191
Indonesia                                               507         148
Ireland                                                 501         209
...                                                     ...         ...
Fiji                                                      5           1
Haiti                                                     5           3
Benin                                                     5           3
Namibia                                                   5           3
Angola                                                    5           2
Botswana                                                  5           1
Monaco                                                    4           2
Togo                                                      4           1
Burkina Faso                                              4           0
Cape Verde                                                3           0
Burundi                                                   3           1
Belize                                                    3           1
Mali                                                      3           1
Guyana                                                    3           2
Liechtenstein                                             3           1
Lao People's Democratic Republic                          3           0
Guinea                                                    3           2
Democratic People's Republic of Korea                     3           1
Barbados                                                  3           1
Lesotho                                                   3           1
Bahamas                                                   3           2
Sierra Leone                                              2           1
Gabon                                                     2           0
Djibouti                                                  2           0
Seychelles                                                2           1
Malawi                                                    2           0
Liberia                                                   2           0
Bhutan                                                    2           1
San Marino                                                2           1
Brunei Darussalam                                         1           0
North Korea                                               1           0
Timor-Leste                                               1           1
Tonga                                                     1           0
Niger                                                     1           1
Dominica                                                  1           1
Papua New Guinea                                          1           0
Saint Kitts and Nevis                                     1           0
Saint Vincent and the Grenadines                          1           0
Sao Tome and Principe                                     1           1
Chad                                                      1           0

[179 rows x 2 columns]

In [315]:
table["PrsntUserPYthon"]=(table["UserPython"]  /    table["AllPeopleEachCountry"])  * 100

In [316]:
table

,AllPeopleEachCountry,UserPython,PrsntUserPYthon
Country,,,
United States,20949,10083,48.131176
India,9061,3105,34.267741
Germany,5866,2451,41.783157
United Kingdom,5737,2384,41.554820
Canada,3395,1558,45.891016
France,2391,1054,44.081974
Brazil,1948,767,39.373717
Poland,1922,751,39.073881
Australia,1903,790,41.513400
Netherlands,1852,767,41.414687
Russian Federation,1694,708,41.794569
Spain,1604,641,39.962594
Italy,1576,625,39.657360
Sweden,1274,496,38.932496
Switzerland,978,460,47.034765
Israel,952,457,48.004202
Turkey,949,371,39.093783
Pakistan,923,251,27.193933
Ukraine,868,246,28.341014
Austria,839,338,40.286055
Czech Republic,764,285,37.303665
Romania,760,253,33.289474
Iran,738,268,36.314363
Belgium,727,296,40.715268
China,664,297,44.728916
Bulgaria,659,181,27.465857
Mexico,642,245,38.161994
South Africa,627,202,32.216906
Denmark,617,246,39.870340
Bangladesh,605,204,33.719008
Norway,574,232,40.418118
Greece,556,226,40.647482
Argentina,553,191,34.538879
Finland,546,266,48.717949
Portugal,525,182,34.666667
New Zealand,524,236,45.038168
Nigeria,522,152,29.118774
Hungary,513,191,37.231969
Indonesia,507,148,29.191321
Ireland,501,209,41.716567
...,...,...,...
Fiji,5,1,20.000000
Haiti,5,3,60.000000
Benin,5,3,60.000000
Namibia,5,3,60.000000
Angola,5,2,40.000000
Botswana,5,1,20.000000
Monaco,4,2,50.000000
Togo,4,1,25.000000
Burkina Faso,4,0,0.000000
Cape Verde,3,0,0.000000
Burundi,3,1,33.333333
Belize,3,1,33.333333
Mali,3,1,33.333333
Guyana,3,2,66.666667
Liechtenstein,3,1,33.333333
Lao People's Democratic Republic,3,0,0.000000
Guinea,3,2,66.666667
Democratic People's Republic of Korea,3,1,33.333333
Barbados,3,1,33.333333
Lesotho,3,1,33.333333
Bahamas,3,2,66.666667
Sierra Leone,2,1,50.000000
Gabon,2,0,0.000000
Djibouti,2,0,0.000000
Seychelles,2,1,50.000000
Malawi,2,0,0.000000
Liberia,2,0,0.000000
Bhutan,2,1,50.000000
San Marino,2,1,50.000000
Brunei Darussalam,1,0,0.000000
North Korea,1,0,0.000000
Timor-Leste,1,1,100.000000
Tonga,1,0,0.000000
Niger,1,1,100.000000
Dominica,1,1,100.000000
Papua New Guinea,1,0,0.000000
Saint Kitts and Nevis,1,0,0.000000
Saint Vincent and the Grenadines,1,0,0.000000
Sao Tome and Principe,1,1,100.000000
Chad,1,0,0.000000

In [261]:
table.loc["Turkey"]

AllPeopleEachCountry    949.000000
UserPython              371.000000
PrsntUserPYthon          39.093783
Name: Turkey, dtype: float64

In [293]:
table=country_grp["EdLevel"].apply(lambda x : x.value_counts(normalize=True))

In [306]:
table.loc["United Kingdom"]

Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.454903
Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.222540
Some college/university study without earning a degree                                0.145562
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.094124
Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.049116
Associate degree                                                                      0.015896
Primary/elementary school                                                             0.008216
I never completed any formal education                                                0.004822
Professional degree (JD, MD, etc.)                                                    0.004822
Name: EdLevel, dtype: float64

In [330]:
edLevel=df.groupby("Country")

In [331]:
arda=edLevel["EdLevel"].apply(lambda x : x.value_counts(normalize=True))

In [332]:
arda

Country
Afghanistan                           Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.435897
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.128205
                                      Associate degree                                                                      0.102564
                                      Primary/elementary school                                                             0.102564
                                      I never completed any formal education                                                0.076923
                                      Some college/university study without earning a degree                                0.076923
                                      Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.051282
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.025641
Albania                               Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.456790
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.296296
                                      Some college/university study without earning a degree                                0.135802
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.086420
                                      Professional degree (JD, MD, etc.)                                                    0.012346
                                      Primary/elementary school                                                             0.012346
Algeria                               Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.475410
                                      Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.254098
                                      Some college/university study without earning a degree                                0.122951
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.049180
                                      Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.024590
                                      Professional degree (JD, MD, etc.)                                                    0.024590
                                      Associate degree                                                                      0.016393
                                      Primary/elementary school                                                             0.016393
                                      I never completed any formal education                                                0.016393
Andorra                               I never completed any formal education                                                0.285714
                                      Primary/elementary school                                                             0.285714
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.285714
                                      Some college/university study without earning a degree                                0.142857
Angola                                Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.333333
                                      Primary/elementary school                                                             0.333333
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.333333
Antigua and Barbuda                   Primary/elementary school                                                             0.285714
                                      I never completed any formal education                                                0.285714
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.142857
                                      Associate degree                                                                      0.142857
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.142857
Argentina                             Some college/university study without earning a degree                                0.363977
                                      Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.240150
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.148218
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.103189
                                      Professional degree (JD, MD, etc.)                                                    0.056285
                                                                                                                              ...
Uruguay                               Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.063636
                                      Professional degree (JD, MD, etc.)                                                    0.036364
                                      Primary/elementary school                                                             0.027273
                                      Associate degree                                                                      0.009091
                                      Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.009091
Uzbekistan                            Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.621622
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.108108
                                      Some college/university study without earning a degree                                0.108108
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.081081
                                      Primary/elementary school                                                             0.027027
                                      Professional degree (JD, MD, etc.)                                                    0.027027
                                      Associate degree                                                                      0.027027
Venezuela, Bolivarian Republic of...  Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.329412
                                      Some college/university study without earning a degree                                0.317647
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.117647
                                      Professional degree (JD, MD, etc.)                                                    0.094118
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.082353
                                      Associate degree                                                                      0.035294
                                      Primary/elementary school                                                             0.011765
                                      Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.011765
Viet Nam                              Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.437500
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.165179
                                      Some college/university study without earning a degree                                0.125000
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.098214
                                      Associate degree                                                                      0.062500
                                      I never completed any formal education                                                0.049107
                                      Primary/elementary school                                                             0.031250
                                      Professional degree (JD, MD, etc.)                                                    0.017857
                                      Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.013393
Yemen                                 Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.789474
                                      Some college/university study without earning a degree                                0.157895
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.052632
Zambia                                Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.583333
                                      Some college/university study without earning a degree                                0.250000
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.083333
                                      Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           0.083333
Zimbabwe                              Bachelor’s degree (BA, BS, B.Eng., etc.)                                              0.500000
                                      Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.236842
                                      Some college/university study without earning a degree                                0.236842
                                      Other doctoral degree (Ph.D, Ed.D., etc.)                                             0.026316
Name: EdLevel, Length: 1084, dtype: float64

In [379]:
df["YearsCode"]=df["YearsCode"].replace(['Less than 1 year','More than 50 years'],[0,51])

In [381]:
df["YearsCode"]=df["YearsCode"].astype(float)
df["YearsCode"].unique()

array([ 4., nan,  3., 16., 13.,  6.,  8., 12.,  2.,  5., 17., 10., 14.,
       35.,  7.,  0., 30.,  9., 26., 40., 19., 15., 20., 28., 25.,  1.,
       22., 11., 33., 50., 41., 18., 34., 24., 23., 42., 27., 21., 36.,
       32., 39., 38., 31., 37., 51., 29., 44., 45., 48., 46., 43., 47.,
       49.])

In [383]:
df["YearsCode"].mean()
df["YearsCode"].median()

np.float64(9.0)

In [9]:
sex=df["Country"]=="Turkey"

In [13]:
sex=df.loc[sex]

In [15]:
sex.to_excel("data/modified.xlsx")

In [17]:
test=pd.read_excel("data/modified.xlsx",index_col="Respondent")

In [19]:
test

,Unnamed: 0,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
28,27,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance, marketing)","Taken an online course in programming or software development (e.g. a MOOC);Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software",2-9 employees,"Designer;Developer, front-end;Developer, full-stack",10,35,5,Very satisfied,Very satisfied,Very confident,No,No,"I’m not actively looking, but I am open to new opportunities",More than 4 years ago,Complete a take-home project,No,Financial performance or funding status of the company or organization;Remote work options;Flex time or a flexible schedule,"My job status changed (promotion, new job, etc.)",TRY,Turkish lira,NaN,Monthly,NaN,40.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",NaN,All or almost all the time (I'm full-time remote),Home,Far above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Developers and management have nearly equal input into purchasing new technology,I have some influence,JavaScript;TypeScript,JavaScript,MariaDB;MongoDB,MariaDB;MongoDB,NaN,NaN,React.js;Vue.js,Vue.js,Node.js,Node.js,Visual Studio Code,Windows,Development;Testing;Production,Not at all,NaN,No,SIGH,Yes,Instagram,Neither,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,NaN,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","No, not at all",NaN,NaN,NaN,NaN,NaN
123,122,I am a developer by profession,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, electrical, mechanical)","Taken an online course in programming or software development (e.g. a MOOC);Participated in a full-time developer training program or bootcamp;Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder)","1,000 to 4,999 employees","Developer, back-end;Developer, front-end;Developer, full-stack",6,19,3,Very satisfied,Very satisfied,Somewhat confident,Yes,Not sure,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Complete a take-home project;Solve a brain-teaser style puzzle;Interview with people in peer roles;Interview with people in senior / management roles",Yes,Office environment or company culture;How widely used or impactful my work output would be;Flex time or a flexible schedule,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",TRY,Turkish lira,8000.0,Monthly,18432.0,45.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely","Meetings;Non-work commitments (parenting, school work, hobbies, etc.);Toxic work environment",Less than once per month / Never,Home,A little above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers typically have the most influence on purchasing new technology,I have some influence,HTML/CSS;JavaScript;TypeScript,JavaScript;Python;TypeScript,NaN,Couchbase;Redis,NaN,Arduino;Docker;Kubernetes;Raspberry Pi;Slack,Angular/Angular.js;ASP.NET;jQuery;React.js;Vue.js,Express;React.js;Vue.js,NaN,Node.js;React Native;TensorFlow,Visual Studio Code,MacOS,"Production;Outside of work, for personal projects",Non-currency applications of blockchain,NaN,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2014,Multiple times per day,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Contribute to a library of information,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,24.0,Too long,Easy
240,238,I am a student who is learning to code,Yes,Never,"OSS is, on average, of LOWER quality than proprietary / closed source software","Not employed, and not looking for work",Turkey,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,"Taken an online course in programming or software development (e.g. a MOOC);Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,2,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;Python;SQL,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;Python;Scala;SQL,Oracle;PostgreSQL,Cassandra;MongoDB;Oracle;PostgreSQL,Linux;Windows,AWS;Linux;Raspberry Pi,NaN,NaN,NaN,Apache Spark;Hadoop;Pandas;TensorFlow;Xamarin,Atom;IntelliJ;PyCharm,Linux-based,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,WhatsApp,Neither,Username,NaN,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Get a sense of belonging to the developer community,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Overflow,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are",Neutral,A lot more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Courses on technologies you're interested in,21.0,Too long,Neither easy nor difficult
635,632,I am a developer by profession,No,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",Turkey,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Mathematics or statistics,"Taken an online course in programming or software development (e.g. a MOOC);Taught yourself a new language, framework, or tool without taking a formal course","Just me - I am a freelancer, sole proprietor, etc.","Developer, back-end",20,16,2,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,Write any code;Complete a take-home project;Solve a brain-teaser style puzzle;Interview with people in senior / management roles,No,Office environment or company culture;Remote work options;Flex time or a flexible schedule,I was preparing for a job search,USD,United States dollar,10000.0,Yearly,10000.0,40.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns","Lack of support from management;Non-work commitments (parenting, school work, hobbies, etc.);Toxic work environment",All or almost all the time (I'm full-time remote),Home,Average,No,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;JavaScript;Python,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Python;Ruby,MongoDB;PostgreSQL;SQLite,SQLite,AWS;Docker;Linux;MacOS,AWS;Docker;Linux;MacOS,Flask;Ruby on Rails,Flask;Ruby on Rails,NaN,Pandas;Torch/PyTorch,IPython / Jupyter;Sublime Text,MacOS,Development;Testing,NaN,Useful across many domains and could change many aspects of our lives,Yes,Also Yes,Yes,I don't use social media,Neither,Username,I don't remember,Daily or almost daily,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Somewhat less welcome now than last year,NaN,36.0,Appropriate in length,Difficult
673,670,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Not employed, and not looking for work",Turkey,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;C#;HTML/CSS;JavaScript;PHP;SQL,C;C++;F#;Java;PHP;SQL,SQLite,Microsoft SQL Server;MySQL,Windows,Android;Windows,NaN,NaN,.NET;.NET Core,.NET;.NET Core;Unreal Engine,Eclipse;Notepad++;Visual Studio,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,No,Yes,What?,YouTube,Online,Handle,2015,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Contribute to a library of information;Get a sense of belonging to the developer community,1-2 times per week,Stack Overflow was slightly faster,60+ minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a job board","No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in,13.0,Appropriate in length,Neither easy nor difficult
699,696,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than proprietary / closed source software",Employed full-time,Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, electrical, mechanical)","Taken an online course in programming or software development (e.g. a MOOC);Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, full-stack;Developer, mobile",8,20,4,Slightly dissatisfied,Slightly satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new opportunities",3-4 years ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,Specific department or team I'd be working on;Office environment or company culture;Opportunities for professional development,I was preparing for a job search,TRY,Turkish lira,10000.0,Monthly,23040.0,45.0,There's no schedule or spec; I work on what seems most important or urgent,Being tasked with non-development work;Distracting work environment,Less than once per month / Never,Office,Far above average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,Bash/Shell/PowerShell;C;C++;C#;HTML/CSS;JavaScript;SQL,C;C++;C#;JavaScript,MySQL;SQLite,SQLite,Android;Linux;Raspberry Pi;Windows,Android;Linux;Raspberry Pi;Windows,ASP.NET;jQuery,ASP.NET;jQuery,.NET;Xamarin,.NET;Xamarin,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,Yes,I don't use social media,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Pass the time / relax,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Overflow,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;Courses on technologies you're interested in,28.0,Appropriate in length,Easy
718,715,I am a developer by profession,Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Turkey,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taken an online course in programming or software development (e.g. a MOOC);Taken a part-time in-person course in programming or software development;Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, game or graphics;System administrator",20,9,14,Slightly satisfied,Slightly satisfied,Somewhat confident,Yes,I am already a manager,I am not interested in new job opportunities,More than 4 years ago,Interview with people in senior / management roles,No,Remote work options;How widely used or impactful my work output would be;Flex time or a flexible schedule,I was preparing for a job search,TRY,Turkish lira,160000.0,Yearly,30720.0,45.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Being tasked with non-development work;Meetings;Not enough people for the workload,A few days each month,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",NaN,"No, but I think we should",Developers and management have nearly equal input into purchasing new technology,I have a great deal of influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript;WebAssembly,Microsoft SQL Server;MySQL,Elasticsearch;Microsoft SQL Server;SQLite;Other(s):,Android;Arduino;iOS;Linux;Windows;Other(s):,Android;Arduino;Docker;iOS;Linux;Microsoft Azure;Windows;Other(s):,ASP.NET;jQuery;React.js,Angular/Angular.js;ASP.NET;React.js,.NET;.NET Core;React Native;Unity 3D,.NET;.NET Core;React Native;Unity 3D,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,Useful for immutable record keeping outside of currency,No,Yes,Yes,NaN,In real life (in person),Username,2012,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,11-30 minutes,No,NaN,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Courses on technologies you're interested in,35.0,Too long,Easy
803,800,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Turkey,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or software engineering",NaN,10 to 19 employees,"Data scientist or machine learning specialist;Developer, desktop or enterprise applications;Developer, embedded applications or devices;DevOps specialist;Senior executive/VP",25,12,18,Neither satisfied nor dissatisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self employed,NaN,No,Industry that I'd be working in;Office environment or company culture;Flex time or a flexible schedule,I was preparing for a job search,TRY,Turkish lira,12000.0,Monthly,27648.0,45.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns","Distracting work environment;Non-work commitments (parenting, school work, hobbies, etc.);Not enough people for the workload",It's complicated,Home,Average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have a great deal of influence,Assembly;Bash/Shell/PowerShell;C;C++;Java;JavaScript;Python;SQL,Bash/Shell/PowerShell;C;C++;JavaScript;Python,NaN,NaN,AWS;Linux,AWS;Linux,NaN,NaN,TensorFlow;Torch/PyTorch,Node.js;TensorFlow;Torch/PyTorch,Emacs,Linux-based,"Outside of work, for personal projects",Not at all,Useful for immutable record keeping outside of currency,No,Yes,Yes,Reddit,Online,Username,2008,Multiple times per day,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,NaN,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers,39.0,Too long,Easy
968,964,I am a developer by profession,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Turkey,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Another engineering discipline (ex. civil, electrical, mechanical)","Taught yourself a new language, framework, or tool without taking a formal course;Contributed to open source software",10 to 19 employees,"Database administrator;Developer, back-end;Developer, embedded applications or devices;Engineering manager;System administrator",15,13,11,Very satisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,1-2 years ago,Interview with people in peer roles;Interview with people in senior / management roles,No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company culture;Remote work options",I was preparing for a job search,TRY,Turkish lira,8200.0,Monthly,18888.0,55.0,There's no schedule or spec; I work on what seems most important or urgent,Being tasked with non-development work;Distracting work environment,"More than half, but not all, the time",Home,Far above average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the developers do it on their own",Developers typically have the most influence on purchasing new technology,I have a great deal of influence,Bash/Shell/PowerShell;C;Go;Python;SQL,C;Go;Python;Rust,MariaDB;MySQL;SQLite,MongoDB;Redis;Other(s):,Linux;Raspberry Pi;Windows,Android;Docker;Kubernetes;Linux;Raspberry Pi;Windows,Django,Django;Flask;Vue.js,NaN,Xamarin,Notepad++;PyCharm;Visual Studio;Visual Studio Code,Windows,Production,Not at all,NaN,Yes,Yes,Yes,YouTube,Neither,Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,31.0,Appropriate in length,Easy

In [35]:
sex.to_json("data/modified.json", orient="records",lines=True)
#Thats very good actually

In [36]:
test=pd.read_json("data/modified.json", orient="records",lines=True)

In [58]:
from sqlalchemy import create_engine
import psycopg2

In [60]:
engine = create_engine("postgresql+psycopg2://postgres:"password here"@localhost:5432/pandas_db")

In [61]:
sex.to_sql("sample_table",engine,if_exists="replace")

143

In [62]:
sql_df=pd.read_sql("sample_table",engine,index_col="Respondent")

In [65]:
posts_df = pd.read_json('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/master/Python/Flask_Blog/snippets/posts.json')

In [67]:
posts_df.head(3)

,title,content,user_id
0,My Updated Post,My first updated post!\r\n\r\nThis is exciting!,1
1,A Second Post,This is a post from a different user...,2
2,Top 5 Programming Lanaguages,"Te melius apeirian postulant cum, labitur admodum cu eos! Tollit equidem constituto ut has. Et per ponderum sadipscing, eu vero dolores recusabo nec! Eum quas epicuri at, eam albucius phaedrum ad, no eum probo fierent singulis. Dicat corrumpit definiebas id usu, in facete scripserit eam.\r\n\r\nVim ei exerci nusquam. Agam detraxit an quo? Quo et partem bonorum sensibus, mutat minimum est ad. In paulo essent signiferumque his, quaestio sadipscing theophrastus ad has. Ancillae appareat qualisque ei has, usu ne assum zril disputationi, sed at gloriatur persequeris.",1